apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n5mkfqg4x-nodejs
  janus-idp.io/tekton: n5mkfqg4x-nodejs
  backstage.io/kubernetes-id: n5mkfqg4x-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n5mkfqg4x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
